GET http://localhost:8080/api/chirps
?author_id=1

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
"email": "walt@breakingbad.com",
"password": "123456"
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
"email": "walt@breakingbad.com",
"password": "123456"
}

###
POST http://localhost:8080/api/chirps
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHktYWNjZXNzIiwic3ViIjoiMSIsImV4cCI6MTcwNjM1Nzk5NiwiaWF0IjoxNzA2MzU0Mzk2fQ.K8ASqzjjXvgvpw5--DeIJM-Uw3_ih7T5qXduraljs8g"
Content-Type: application/json

{
    "body": "I'm the one who knocks!"
}