POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "I had something interesting for breakfast"
}

###


GET  http://localhost:8080/api/chirps

###
GET  http://localhost:8080/api/chirps/2

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "password": "04234",
  "email": "user@example.com"
}

###


POST http://localhost:8080/api/users
Content-Type: application/json

{
  "password": "04234",
  "email": "lane@example.com"
}

###

POST http://localhost:8080/api/login
Content-Type: application/json

{
  "password": "04234",
  "email": "lane@example.com",
  "expires_in_seconds": 2
}