
POST http://localhost:8080/api/polka/webhooks
Content-Type: application/json

{
  "data": {
    "user_id": 1
  },
  "event": "user.upgraded"
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "walt@breakingbad.com",
  "password": "123456"
}

